# Generated by Django 3.0.6 on 2020-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200522_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='conpassword',
            field=models.CharField(default='prayag', max_length=50),
            preserve_default=False,
        ),
    ]
