# Generated by Django 3.0.6 on 2020-05-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_signup_conpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='conpassword',
            new_name='conforpassword',
        ),
    ]
