# Generated by Django 3.0.6 on 2020-05-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20200522_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='conforpassword',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
