# Generated by Django 3.0.6 on 2020-05-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topi', '0002_auto_20200526_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
