# Generated by Django 3.0.6 on 2020-05-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Topi', '0006_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
    ]
