# Generated by Django 3.0.6 on 2020-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topi', '0009_auto_20200530_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
