# Generated by Django 3.0.6 on 2020-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topi', '0010_auto_20200531_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('Ture', 'Yes'), ('False', 'No')], default='No', max_length=5),
        ),
    ]
